/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.Toolkit;

/**
 *
 * @author hcr4716
 */
public class Instruction extends javax.swing.JFrame {

    /**
     * Creates new form Instruction
     */
    public Instruction() {
        initComponents();
        String str = "<html>Welcome to Kiwi Island! Use WASD key board to move. "
                + "<br/>Use trap to catch predators. When all predators are collected, you win. "
                + "<br/>Collect food and use to restore your stamina. When your stamina is 0, you lose. "
                + "<br/>Kiwis can be collected. Have fun!</html>";
        this.contentLable.setText(str);
        CenterPanel();
    }
public void CenterPanel(){
    int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setLocation((width/2)-200, (height/2)-150);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backToStartPageBotton = new javax.swing.JButton();
        contentLable = new javax.swing.JLabel();
        instructionLable = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backToStartPageBotton.setText("Back to start page");
        backToStartPageBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToStartPageBottonActionPerformed(evt);
            }
        });

        contentLable.setText("jLabel1");

        instructionLable.setText("Instruction");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(contentLable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(backToStartPageBotton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(instructionLable)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(instructionLable)
                .addGap(18, 18, 18)
                .addComponent(contentLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(backToStartPageBotton)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToStartPageBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToStartPageBottonActionPerformed
        this.setVisible(false); 
        StartPage sp = new StartPage();
         sp.setVisible(true);
    }//GEN-LAST:event_backToStartPageBottonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToStartPageBotton;
    private javax.swing.JLabel contentLable;
    private javax.swing.JLabel instructionLable;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
