/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.Toolkit;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author hcr4716
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        CenterPanel();
    }
public void CenterPanel(){
    int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height;
    this.setLocation((width/2)-200, (height/2)-150);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameBptton = new javax.swing.JButton();
        HiScoreBotton = new javax.swing.JButton();
        instructionBotton = new javax.swing.JButton();
        titleLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newGameBptton.setText("New Game");
        newGameBptton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBpttonActionPerformed(evt);
            }
        });

        HiScoreBotton.setText("Hi-Score");
        HiScoreBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HiScoreBottonActionPerformed(evt);
            }
        });

        instructionBotton.setText("Instruction");
        instructionBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionBottonActionPerformed(evt);
            }
        });

        titleLable.setText("   Kiwi Island");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newGameBptton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HiScoreBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instructionBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(newGameBptton)
                .addGap(32, 32, 32)
                .addComponent(HiScoreBotton)
                .addGap(27, 27, 27)
                .addComponent(instructionBotton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameBpttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBpttonActionPerformed
          this.setVisible(false); 
        KiwiCountUI kc = new KiwiCountUI(new Game());
        kc.setVisible(true);
    }//GEN-LAST:event_newGameBpttonActionPerformed

    private void HiScoreBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HiScoreBottonActionPerformed
        this.setVisible(false);
        HiScorePage HS = new HiScorePage();
        HS.setVisible(true);

    }//GEN-LAST:event_HiScoreBottonActionPerformed

    private void instructionBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionBottonActionPerformed
        
        this.setVisible(false);
        Instruction  IS  = new Instruction();
        IS.setVisible(true);
    }//GEN-LAST:event_instructionBottonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HiScoreBotton;
    private javax.swing.JButton instructionBotton;
    private javax.swing.JButton newGameBptton;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
}
